WIP Feature/task 12: logic of favorite
ArtemZagorovski/NewsApp pull request #27
Opened 2020-09-16 13:52 UTC by ArtemZagorovski

2020-09-16 14:37 UTC, ArtemZagorovski commented on NewsApp/NewsApp/Application/AppCoordinator.swift
> +    func lounch() -> UITabBarController {
a

2020-09-16 14:37 UTC, ArtemZagorovski commented on NewsApp/NewsApp/Application/FavouriteNewsContractProtocols.swift
> +import Foundation
Удалить

2020-09-16 14:37 UTC, ArtemZagorovski commented on NewsApp/NewsApp/Application/NewsCoordinator.swift
> +        let serviceManager = serviceContainer.serviceManager
передать непосредственно сервис

2020-09-16 14:37 UTC, ArtemZagorovski commented on NewsApp/NewsApp/CoreDataStack/CoreDataStack.swift
> +    static var persistentContainer: NSPersistentContainer = {
так быть не должно

2020-09-16 14:37 UTC, ArtemZagorovski commented on NewsApp/NewsApp/MVC/Controller/FavouriteNewsController.swift
> +    func viewDidScrollToEnd() {
пустого метода быть не должно

2020-09-16 14:37 UTC, ArtemZagorovski commented on NewsApp/NewsApp/MVC/Controller/FavouriteNewsController.swift
> +
здесь должно быть что-то ещё...

2020-09-16 14:37 UTC, ArtemZagorovski commented on NewsApp/NewsApp/MVC/Model/DefaultNewsManager.swift
> +        serviceManager.getRemoteData(page: page)
какой-такой ремоут

2020-09-16 14:37 UTC, ArtemZagorovski commented on NewsApp/NewsApp/MVC/Model/FavouriteNewsManager.swift
> +
пустых методов быть не должно

2020-09-16 14:37 UTC, ArtemZagorovski commented on NewsApp/NewsApp/MVC/Model/FavouriteNewsManager.swift
> +        serviceManager.getLocalData()
кто такой локал

2020-09-16 14:37 UTC, ArtemZagorovski commented on NewsApp/NewsApp/MVC/Model/FavouriteNewsManager.swift
> +    func updateFavourite(with news: News, closure: () -> ()) {
add to favorite

2020-09-16 14:37 UTC, ArtemZagorovski commented on NewsApp/NewsApp/MVC/View/CustomCells/NewsCell.swift
> +        newsImage.image = viewModel.image
newsImageView

2020-09-16 14:37 UTC, ArtemZagorovski commented on NewsApp/NewsApp/MVC/View/CustomCells/NewsCell.swift
> +        DispatchQueue.main.async {
убрать

2020-09-16 14:37 UTC, ArtemZagorovski commented on NewsApp/NewsApp/MVC/View/CustomCells/NewsCell.swift
> +    func configure(with viewModel: NewsViewModel) {
методы и переменные в перемешку

2020-09-16 14:37 UTC, ArtemZagorovski commented on NewsApp/NewsApp/MVC/View/CustomCells/NewsCell.swift
> +        favouriteButton.setImage(UIImage(systemName: Constants.SystemWords.flameImageName), for: .normal)
у родителя надо вызвать

2020-09-16 14:37 UTC, ArtemZagorovski commented on NewsApp/NewsApp/MVC/View/News+initFromNewsModel.swift
> +    convenience init(viewModel: NewsViewModel) {
в контроллер

2020-09-18 06:53 UTC, vitali-kazakevich requested changes

2020-09-18 06:53 UTC, vitali-kazakevich commented on NewsApp/NewsApp/Application/CoordinatorProtocols.swift
> +protocol DetailsManager {
не менеджер. Менеджер это обо всем и ни о чем.

DetailsShowable

по протоколу должно быть понятно для чего он

2020-09-18 06:53 UTC, vitali-kazakevich commented on NewsApp/NewsApp/Application/CoordinatorProtocols.swift
> +        guard let view = view as? UIViewController else { return }
почему тип параметра NewsView.. чтобы что-то показать, тебе нужен любой вью-контроллер.
а так ты притянул сюда зависимость от своего какого-то вью

2020-09-18 06:53 UTC, vitali-kazakevich commented on NewsApp/NewsApp/Application/NewsContractProtocols.swift
> +    func viewDidTapFavouriteButton(for viewModel: NewsViewModel, closure: @escaping () -> ())
может все таки кложер можно назвать нормально?
ччтобы было понятно что за кложур

2020-09-18 06:53 UTC, vitali-kazakevich commented on NewsApp/NewsApp/Application/NewsContractProtocols.swift
> +    func addToFavorite(_ news: News, closure: @escaping () -> ())
а ремув?

2020-09-18 06:53 UTC, vitali-kazakevich commented on NewsApp/NewsApp/Application/SceneDelegate.swift
> +        self.window?.rootViewController = AppCoordinator().launch()
Артем, названия.
они должны соответсвовать и тому что происходит внутри метода и тому что из них возвращается

2020-09-18 06:53 UTC, vitali-kazakevich commented on NewsApp/NewsApp/Application/TabBarCoordinator.swift
> +    private let newsViewController: UIViewController
зачем здесь сохраняются контроллеры?

2020-09-18 06:53 UTC, vitali-kazakevich commented on NewsApp/NewsApp/Application/TabBarCoordinator.swift
> +        tabBarController.tabBar.tintColor = #colorLiteral(red: 0.5568627715, green: 0.3529411852, blue: 0.9686274529, alpha: 1)
вау...
добавь цвет ассетом мб?
или создай через UIColor

2020-09-18 06:53 UTC, vitali-kazakevich commented on NewsApp/NewsApp/MVC/Controller/FavouriteNewsController.swift
> +        DispatchQueue.main.async {
выглядит как будто ты рандомно втсавляешь эту строчку
DispatchQueue.main.async {

2020-09-18 06:53 UTC, vitali-kazakevich commented on NewsApp/NewsApp/MVC/View/NewsViewController.swift
> +        delegate?.viewDidLoad()
вот это поворот..
не кажется ли тебе, что тут что-то не так?)

2020-09-18 06:53 UTC, vitali-kazakevich commented on NewsApp/NewsApp/MVC/View/NewsViewController.swift
> +        viewModels = []
мне кажется здесь это не нужно

2020-09-18 06:53 UTC, vitali-kazakevich commented on NewsApp/NewsApp/MVC/View/NewsViewController.swift
> +    func showAnEmptyState() {
не соответствует название метода

2020-09-18 06:53 UTC, vitali-kazakevich commented on NewsApp/NewsApp/MVC/View/NewsViewController.swift
> +        if viewModels.isEmpty {
emptyStateLabel.isHidden = !viewModels.isEmpty

2020-09-18 06:53 UTC, vitali-kazakevich commented on NewsApp/NewsApp/MVC/View/NewsViewController.swift
> +                if self.viewModels.filter({ $0.isFavourite == true }).count == self.viewModels.count {
$0.isFavourite == true. => $0.isFavourite

2020-09-18 06:53 UTC, vitali-kazakevich commented on NewsApp/NewsApp/MVC/View/NewsViewController.swift
> +                if self.viewModels.filter({ $0.isFavourite == true }).count == self.viewModels.count {
ужс. эта логика во вью контроллере нас не устравивает.
это связано с твоим методом адФаворит
его нужно либо переименовать как-то и добавить параметр который будет говорить, удалялся или добавлялся фаворит

либо добавить второй метод

2020-09-18 06:53 UTC, vitali-kazakevich commented on NewsApp/NewsApp/Services/ServiceManager.swift
> +    weak var favouriteDelegate: NewsServiceCoordinatorDelegate?
не, давай ка один делегат

2020-09-18 06:54 UTC, vitali-kazakevich commented
плюс тут есть коммиты из других веток. 
если тебе что-то нужно, то тебе нужно ветку создавать от туда где это что-то есть

2020-09-18 08:27 UTC, ArtemZagorovski commented on NewsApp/NewsApp/Services/ServiceManager.swift
> +    weak var favouriteDelegate: NewsServiceCoordinatorDelegate?
Сделать один делегат не проблема, но тогда добавление страницы надо будет вешать не на коллбек либо убирать его

2020-09-18 15:43 UTC, ArtemZagorovski commented on NewsApp/NewsApp/Services/NewsController.swift
> +
Не должно быть пустых методов

2020-09-18 15:43 UTC, ArtemZagorovski commented on NewsApp/NewsApp/MVC/Controller/FavouriteNewsController.swift
> +
Аналогично про пустой метод

2020-09-21 11:07 UTC, vitali-kazakevich requested changes

2020-09-21 11:07 UTC, vitali-kazakevich commented on NewsApp/NewsApp/Application/FavouriteNewsCoordinator.swift
> +        guard let model = model as? DefaultNewsManager else { return UIViewController() }
каст убрать

2020-09-21 11:07 UTC, vitali-kazakevich commented on NewsApp/NewsApp/Application/NewsContractProtocols.swift
> +    func changeVisibilityOfAnEmptyState()
убери эту хуню

2020-09-21 11:07 UTC, vitali-kazakevich commented on NewsApp/NewsApp/Application/TabBarCoordinator.swift
> +        let model = DefaultNewsManager(apiService: apiService, dbService: dbService)
давай сделаем модель как сервис, а дб и апи спрячем в ней

2020-09-21 11:07 UTC, vitali-kazakevich commented on NewsApp/NewsApp/Application/TabBarCoordinator.swift
> +    private func generateNavigationController(rootViewController: UIViewController, title: String, image: UIImage) -> UIViewController {
make

2020-09-21 11:07 UTC, vitali-kazakevich commented on NewsApp/NewsApp/MVC/Controller/FavouriteNewsController.swift
> +        view?.stopAnimateActivity()
на фаворитах анимация снизу не должна показываться

2020-09-21 11:07 UTC, vitali-kazakevich commented on NewsApp/NewsApp/MVC/Controller/FavouriteNewsController.swift
> +        guard let view = view as? UIViewController else { return }
каста быть не должно

2020-09-21 11:07 UTC, vitali-kazakevich commented on NewsApp/NewsApp/MVC/Model/DefaultNewsManager.swift
> +        let equals = newsFromBD.filter { $0.id == news.id }
не может быть несколько одинаковых новостей

2020-09-21 11:07 UTC, vitali-kazakevich commented on NewsApp/NewsApp/MVC/Model/DefaultNewsManager.swift
> +        if text.isEmpty {
копипаста

2020-09-21 11:07 UTC, vitali-kazakevich commented on NewsApp/NewsApp/MVC/Model/DefaultNewsManager.swift
> +        newsFromBD.map {$0.isFavourite = true}
пробел

2020-09-22 06:29 UTC, vitali-kazakevich requested changes

2020-09-22 06:29 UTC, vitali-kazakevich commented on NewsApp/NewsApp/Services/NewsController.swift
> +    func viewDidTapFavouriteButton(for viewModel: NewsViewModel, isFavorite: Bool, refreshCell: @escaping () -> ()) {
определись либо "o" либо "ou"

2020-09-22 06:29 UTC, vitali-kazakevich commented on NewsApp/NewsApp/Services/NewsController.swift
> +    func viewDidTapFavouriteButton(for viewModel: NewsViewModel, isFavorite: Bool, refreshCell: @escaping () -> ()) {
по названию непонятно какой смысл несет параметр isFavorite.
либо это текущий статус новости либо тот на который меняется

2020-09-22 06:29 UTC, vitali-kazakevich commented on NewsApp/NewsApp/Services/NewsController.swift
> +        model.filter(favorite: false, for: term)
а фильтрация для фаворитных новостей отсутствует что ли?

2020-09-22 06:29 UTC, vitali-kazakevich commented on NewsApp/NewsApp/Services/DBDataLoader.swift
> -            delegate?.didGetAnError(error: error)
почему теперь не обрабатывается ошибка никак?

2020-09-22 06:29 UTC, vitali-kazakevich commented on NewsApp/NewsApp/Services/APIService.swift
> +                        return
обработка ошибки?

2020-09-22 06:29 UTC, vitali-kazakevich commented on NewsApp/NewsApp/MVC/View/NewsViewController.swift
> +                    self.viewModels.remove(at: indexOfCell.row)
ну опять ты эту логику засунул во вью контрoллер

2020-09-22 06:29 UTC, vitali-kazakevich commented on NewsApp/NewsApp/MVC/View/NewsViewController.swift
> +        if self.delegate?.isFavoriteViewController ?? false {
плохое название. метод должен отражать суть
например isPullToRefreshAvailable

2020-09-22 06:29 UTC, vitali-kazakevich commented on NewsApp/NewsApp/MVC/View/NewsViewController.swift
> +        let isNewsViewController = !(delegate?.isFavoriteViewController ?? false)
когда пишешь булевые значения избегай инверсий (!) сложно читается

2020-09-22 06:29 UTC, vitali-kazakevich commented on NewsApp/NewsApp/MVC/View/NewsViewController.swift
> +        view.insertSubview(emptyStateLabel, aboveSubview: tableView)
да добавь ты их по порядку просто!

2020-09-22 06:29 UTC, vitali-kazakevich commented on NewsApp/NewsApp/MVC/View/CustomCells/NewsCell.swift
> +            newsImageView.widthAnchor.constraint(equalToConstant: squareImageSide)]
скобочку на новую строку

2020-09-22 06:29 UTC, vitali-kazakevich commented on NewsApp/NewsApp/MVC/View/CustomCells/NewsCell.swift
> +        NSLayoutConstraint.activate(newsImangeViewConstraints + textStackConstraints + showMoreLabelConstraints + favoriteButtonConstraints)
слишком длинная строка

2020-09-22 06:29 UTC, vitali-kazakevich commented on NewsApp/NewsApp/MVC/View/CustomCells/NewsCell.swift
> +        let one: CGFloat = 1
спасибо кеп.
названия по тому какую роль это играет а не что это

2020-09-22 06:29 UTC, vitali-kazakevich commented on NewsApp/NewsApp/MVC/Model/DefaultNewsManager.swift
> +            news.isFavourite = !news.isFavourite
у bool есть метод toggle

2020-09-22 06:29 UTC, vitali-kazakevich commented on NewsApp/NewsApp/MVC/Model/DefaultNewsManager.swift
> +            news.isFavourite = !news.isFavourite
ну и логика должна быть завязана на параметр в методе

2020-09-22 06:29 UTC, vitali-kazakevich commented on NewsApp/NewsApp/MVC/Controller/FavouriteNewsController.swift
> +
func viewDidPullToRefresh() {}

2020-09-22 07:01 UTC, ArtemZagorovski commented on NewsApp/NewsApp/Services/NewsController.swift
> +        model.filter(favorite: false, for: term)
Присутствует в классе контроллера фавориты новостей с флагом favorite: true

2020-09-22 07:37 UTC, vitali-kazakevich commented on NewsApp/NewsApp/MVC/View/NewsViewController.swift
> +        let isNewsViewController = !(delegate?.isFavoriteViewController ?? false)
метод у делегата назови нормально, это во первых.
во вторых используй гуард и все будет хорошо

2020-09-22 07:57 UTC, ArtemZagorovski commented on NewsApp/NewsApp/MVC/View/NewsViewController.swift
> +        let isNewsViewController = !(delegate?.isFavoriteViewController ?? false)
какой метод у делегата? Если ты про isFavoriteViewController - то это поле, и назвать наоборот, типа IsNewsViewController?

2020-09-22 08:43 UTC, ArtemZagorovski commented on NewsApp/NewsApp/MVC/View/NewsViewController.swift
> +        if self.delegate?.isFavoriteViewController ?? false {
разве тогда это название будет отражать то, что происходит? по факту тут же проверяется доступен или нет, а если доступен - обновляет

2020-09-22 08:43 UTC, ArtemZagorovski commented on NewsApp/NewsApp/MVC/View/NewsViewController.swift
> +                    self.viewModels.remove(at: indexOfCell.row)
я не менял эту логику, она как была здесь так и осталась)

2020-09-22 08:44 UTC, ArtemZagorovski commented on NewsApp/NewsApp/MVC/View/NewsViewController.swift
> +                    self.viewModels.remove(at: indexOfCell.row)
я только поменял проверку типа на поле делегата

2020-09-22 11:17 UTC, vitali-kazakevich commented on NewsApp/NewsApp/MVC/View/NewsViewController.swift
> +                    self.viewModels.remove(at: indexOfCell.row)
ну значит исправь

2020-09-22 11:23 UTC, ArtemZagorovski commented on NewsApp/NewsApp/MVC/View/NewsViewController.swift
> +                    self.viewModels.remove(at: indexOfCell.row)
так а куда мне деть логику работы с элементами вью?

2020-09-23 12:52 UTC, vitali-kazakevich requested changes

2020-09-23 12:52 UTC, vitali-kazakevich commented on NewsApp/NewsApp/Services/ServiceProtocols.swift
> +    func loadNews(page: Int)
локал менеджер не умеет грузить страницы

2020-09-23 12:52 UTC, vitali-kazakevich commented on NewsApp/NewsApp/Services/DBDataLoader.swift
> +                print(error.localizedDescription)
логер

2020-09-23 12:52 UTC, vitali-kazakevich commented on NewsApp/NewsApp/Services/DBDataLoader.swift
> +            print(error.localizedDescription)
логер

2020-09-23 12:52 UTC, vitali-kazakevich commented on NewsApp/NewsApp/Services/DBDataLoader.swift
> +            print(error.localizedDescription)
логер

2020-09-23 12:52 UTC, vitali-kazakevich commented on NewsApp/NewsApp/Services/APIService.swift
> -                    print(error)
добавь логирование

2020-09-23 12:52 UTC, vitali-kazakevich commented on NewsApp/NewsApp/Services/APIService.swift
> +                        print("can't get data from api")
давай добавим энамку с ошибками внутренними

2020-09-23 12:52 UTC, vitali-kazakevich commented on NewsApp/NewsApp/MVC/View/NewsViewController.swift
> +
передвинь под гуард

2020-09-23 12:52 UTC, vitali-kazakevich commented on NewsApp/NewsApp/MVC/View/NewsViewController.swift
>      fileprivate func setDelegats() {
прайват

2020-09-23 12:52 UTC, vitali-kazakevich commented on NewsApp/NewsApp/MVC/View/NewsViewController.swift
> +    //MARK: - ViewController lifecycle methods
пробле

2020-09-23 12:52 UTC, vitali-kazakevich commented on NewsApp/NewsApp/MVC/View/NewsViewController.swift
>  class NewsViewController: UIViewController {
файнл

2020-09-23 12:52 UTC, vitali-kazakevich commented on NewsApp/NewsApp/MVC/View/CustomCells/NewsCell.swift
> +        favoriteButton.setImage(UIImage(systemName: Constants.SystemWords.flameImageName), for: .normal)
favoriteButton.setImage(UIImage(systemName: Constants.SystemWords.flameImageName), for: .normal)

в конфигюрвиз вьюмодел

2020-09-23 12:52 UTC, vitali-kazakevich commented on NewsApp/NewsApp/MVC/View/CustomCells/NewsCell.swift
> +            self.favoriteButton.setImage(UIImage(systemName: Constants.SystemWords.fillFlameImageName), for: .normal)
селф не нужен

2020-09-23 12:52 UTC, vitali-kazakevich commented on NewsApp/NewsApp/MVC/View/CustomCells/NewsCell.swift
> +        let hasMoreText = self.descriptionLabel.actualNumberOfLines() > 3
не нужен селф

2020-09-23 12:52 UTC, vitali-kazakevich commented on NewsApp/NewsApp/MVC/Model/DefaultNewsManager.swift
> +        newsFromBD.forEach {$0.isFavorite = true}
пробелы

2020-09-23 12:52 UTC, vitali-kazakevich commented on NewsApp/NewsApp/MVC/Model/DefaultNewsManager.swift
> +        }
почему else на новой строке

2020-09-23 12:52 UTC, vitali-kazakevich commented on NewsApp/NewsApp/MVC/Model/DefaultNewsManager.swift
> +            guard let indexOfEqual = newsFromBD.firstIndex(of: news) else { return }
условия через запятую в if

2020-09-23 12:52 UTC, vitali-kazakevich commented on NewsApp/NewsApp/MVC/Controller/News+initFromNewsModel.swift
> +import UIKit
проверь  надо ли?

2020-09-23 12:52 UTC, vitali-kazakevich commented on NewsApp/NewsApp/MVC/Controller/FavoriteNewsController.swift
> +
...

2020-09-23 12:52 UTC, vitali-kazakevich commented on NewsApp/NewsApp/Application/TabBarCoordinator.swift
> +        guard let listImage = UIImage(systemName: "list.bullet", withConfiguration: boldConfig),
индентация и код стайл

2020-09-24 07:14 UTC, vitali-kazakevich requested changes

2020-09-24 07:14 UTC, vitali-kazakevich commented on NewsApp/NewsApp/Application/TabBarCoordinator.swift
> +        guard let listImage = UIImage(systemName: "list.bullet", withConfiguration: boldConfig),
!!!!

2020-09-24 07:14 UTC, vitali-kazakevich commented on NewsApp/NewsApp/Helpers/InternetConnectionManager.swift
> +
каким боком это сюда попало?

2020-09-24 07:14 UTC, vitali-kazakevich commented on NewsApp/NewsApp/Helpers/Logger.swift
> +//  NewsApp
а это?

2020-09-24 07:14 UTC, vitali-kazakevich commented on NewsApp/NewsApp/MVC/Model/DefaultNewsManager.swift
> +            guard let indexOfEqual = newsFromBD.firstIndex(of: news) else { return }
!!!!

2020-09-24 07:14 UTC, vitali-kazakevich commented on NewsApp/NewsApp/MVC/Model/DefaultNewsManager.swift
> +        }
!!!!

2020-09-24 07:14 UTC, vitali-kazakevich commented on NewsApp/NewsApp/Services/NewsError.swift
> +    case notAnImageName
"не имя картинки" - ну так себе название

2020-09-24 08:55 UTC, vitali-kazakevich approved these changes

2020-09-24 08:56 UTC, merged