Bugfix/Task 12: Rename pull to refresh method
ArtemZagorovski/NewsApp pull request #41
Opened 2020-09-22 10:21 UTC by ArtemZagorovski

2020-09-22 11:12 UTC, vitali-kazakevich commented on NewsApp/NewsApp/MVC/View/NewsViewController.swift
> +    @objc private func refreshView(sender: UIRefreshControl) {
было такое замечание?

2020-09-22 11:15 UTC, ArtemZagorovski commented on NewsApp/NewsApp/MVC/View/NewsViewController.swift
> +    @objc private func refreshView(sender: UIRefreshControl) {
"метод должен отражать суть"

2020-09-23 05:43 UTC, vitali-kazakevich commented on NewsApp/NewsApp/MVC/View/NewsViewController.swift
>          if isNeedToLoadNewData {
используй гуард, если нужно отсечь какой-то путь выполнения

2020-09-23 05:44 UTC, vitali-kazakevich commented on NewsApp/NewsApp/MVC/View/NewsViewController.swift
>              sender.endRefreshing()
это все еще "показать и спрятать" а не "не показывать"

2020-09-23 09:07 UTC, vitali-kazakevich requested changes

2020-09-23 09:07 UTC, vitali-kazakevich commented on NewsApp/NewsApp/MVC/View/NewsViewController.swift
> +        guard let isLoadMoreAvailable = delegate?.isLoadMoreDataAvailable() else { return }
давай ка все в один ретурн, будет проще

2020-09-23 10:35 UTC, closed without merging