Task-21: news not loading from api on viewWillAppear
ArtemZagorovski/NewsApp pull request #67
Opened 2020-09-28 12:14 UTC by ArtemZagorovski

2020-09-28 14:35 UTC, vitali-kazakevich requested changes

2020-09-28 14:35 UTC, vitali-kazakevich commented on NewsApp/NewsApp/MVC/Model/DefaultNewsManager.swift
> +        if newsFromApi.isEmpty {
проблемы отображения не решаются в модели.

да и в принципе теперь у тебя новости не будут подгружаться при скроле.

2020-09-28 19:04 UTC, vitali-kazakevich requested changes

2020-09-28 19:04 UTC, vitali-kazakevich commented on NewsApp/NewsApp/Services/NewsController.swift
> +        guard view?.viewModels.isEmpty == true else { return }
Никакой логики во вью контроллере:)

2020-09-29 06:34 UTC, ArtemZagorovski commented on NewsApp/NewsApp/Services/NewsController.swift
> +        guard view?.viewModels.isEmpty == true else { return }
это не вью контроллер, это просто контроллер)

2020-09-29 07:13 UTC, vitali-kazakevich requested changes

2020-09-29 07:13 UTC, vitali-kazakevich commented on NewsApp/NewsApp/Application/NewsContractProtocols.swift
>      func updateView(_ news: [NewsViewModel])
зачем тут сет?

2020-09-29 07:16 UTC, ArtemZagorovski commented on NewsApp/NewsApp/Application/NewsContractProtocols.swift
>      func updateView(_ news: [NewsViewModel])
согласен, не нужен

2020-09-29 10:42 UTC, vitali-kazakevich approved these changes

2020-09-29 10:57 UTC, merged