bugfix/Task-22: fix reloading tableView on loadMore
ArtemZagorovski/NewsApp pull request #68
Opened 2020-09-28 12:22 UTC by ArtemZagorovski

2020-09-28 14:36 UTC, vitali-kazakevich requested changes

2020-09-28 14:36 UTC, vitali-kazakevich commented on NewsApp/NewsApp/MVC/View/NewsViewController.swift
> +        if controller?.isLoadMoreDataAvailable() == true {
не понимаю проблемы и тем более почему она так решается

2020-09-29 06:38 UTC, ArtemZagorovski commented on NewsApp/NewsApp/MVC/View/NewsViewController.swift
> +        if controller?.isLoadMoreDataAvailable() == true {
проблема в том, что у меня главный экран не догружал новости по факту, а перезагружал новыми, поэтому их нужно добавлять, а не обновлять на главном экране.

2020-09-29 07:26 UTC, vitali-kazakevich commented on NewsApp/NewsApp/MVC/View/NewsViewController.swift
> +        if controller?.isLoadMoreDataAvailable() == true {
ну и посмотри что у тебя получается.
часть логики с вью моделями делается и проверяется во вью контроллере. часть в контроллере.
считаешь что это хороший подход?

2020-09-29 11:51 UTC, vitali-kazakevich approved these changes

2020-09-29 11:51 UTC, merged